# 基础设置
title: "2341"      # 显示在浏览器标签页
description: "大家在带节奏我退出了"    # 网站简介
url: "https://ktsan-wa.github.io" # 你的网址

# 主题配置
theme: minima             # 必须和 Gemfile 里的主题名一致

# 社交链接（可选）
social_links:
  github: KTsan-WA       # 会自动生成 GitHub 图标链接
